### ISSUE TITLE
Delete empty folders wrong

### ISSUE THREAD

**Issue by whoubeizin** [dy-sh/obsidian-consistent-attachments-and-links#87] opened 2024-03-22 11:16 UTC
I switch on "delete empty folders" option, and specify attchment named "附件". However when i move the note to another folder, the original folder changed into empty one didn't be deleted as excepted. And the empty folder seems not empty
![2024-03-22_191029](https://github.com/dy-sh/obsidian-consistent-attachments-and-links/assets/30174645/30693812-d977-4cbd-a80e-627944ec489a)

**Comment by spaceg00se-r** [comment] 2024-07-20 08:07
I can second that. I have my Vault in iCloud drive and if when I move a note with attachments, the attachments get correctly moved to the new location, but the old folder stays in the source (and is empty). Also triggering the "delete empty folders" action manually does not delete the old folders.

**Comment by suka97** [comment] 2024-07-23 23:46
I have the same issue. New version 2.0.0 didn't solved it

**Comment by mnaoumov** [comment] 2024-07-23 23:50
I am closing this as a duplicate of #90. I need help to reproduce the issue

**Closed by mnaoumov** 2024-07-23 23:50 UTC
