### ISSUE TITLE
Plugin appears to be broken since update?

### ISSUE THREAD

**Issue by Tesgin** [dy-sh/obsidian-consistent-attachments-and-links#83] opened 2024-02-22 02:00 UTC
Plugin no longer working: when I move markdown files to a new folder the links move with it to the user-defined _resource folder, but the links in the note are not properly updated and images can no longer be found.

Didn't used to do that. I'm noticing it since the update 2 days ago

**Comment by mnaoumov** [comment] 2024-02-22 22:59
@Tesgin can you provide a copy of the vault where you can reproduce the issue, so I can reproduce it?

**Comment by mnaoumov** [comment] 2024-02-22 23:03
@Tesgin do you have `Update Links` setting enabled?

**Comment by Tesgin** [comment] 2024-02-22 23:58
I do not

**Comment by mnaoumov** [comment] 2024-02-23 00:01
@Tesgin if you don't have this setting enabled, then the links update is the responsibility of Obsidian itself and the plugin has nothing to do with it

**Comment by Tesgin** [comment] 2024-02-23 00:09
@mnaoumov Thanks for this.

Here's a wetransfer link to download the vault. Not the whole vault but just a handful of folders to demo: https://we.tl/t-heEiAL6qd6

Re: the update links thing, my understanding is that (per the plugin instructions) it's the opposite, that when this is disabled, that gives the plugin the responsibility for updating links:

Required Obsidian settings for the plugin to work properly:

"Files & Links > Automatically update internal links": disabled. The plugin itself is responsible for updating the links. When Obsidian shows a dialog asking to update links, refuse.

**Comment by mnaoumov** [comment] 2024-02-23 00:10
@Tesgin I meant the setting of the current plugin, not the Obsidian one you refer to

**Comment by Tesgin** [comment] 2024-02-23 00:11
I just realized I misunderstood what you are saying. You are correct.  I misspoke. In the plugin, yes, I do have that enabled.  Under "Files and Links" I have that disabled. That was my quote above

**Comment by Tesgin** [comment] 2024-02-23 00:12
Yes, in the plugin I have Update Links enabled

**Comment by DG0lden** [comment] 2024-05-13 15:41
This problem affects me as well: attachments from Evernote are collected in each notes' personal folder under _resources. They are not moved to global "attachments" sub-folder of my current folder as I expect.

Plugin settings are: 
```
{
  "moveAttachmentsWithNote": true,
  "deleteAttachmentsWithNote": true,
  "updateLinks": true,
  "deleteEmptyFolders": true,
  "deleteExistFilesWhenMoveNote": true,
  "changeNoteBacklinksAlt": false,
  "ignoreFolders": [
    ".git/",
    ".obsidian/"
  ],
  "ignoreFiles": [
    "consistency\\-report\\.md"
  ],
  "ignoreFilesRegex": [
    {}
  ],
  "attachmentsSubfolder": "attachments",
  "consistencyReportFile": "consistency-report.md",
  "useBuiltInObsidianLinkCaching": false
}
```

**Comment by eemq** [comment] 2024-05-18 22:16
Any update on a possible fix? Plugin is not working for me either :( 

My console log has this error: 

```
[Consistent Attachments and Links: ]
(plugin:consistent-attachments-and-links:1880 Consistent Attachments and Links:)

SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is a directory) 
/Users/my.name/Library/Mobile Documents/iCloud~md~obsidian/Documents/my_notes/1. Personal/_inbox/_resources

eval @ plugin:consistent-attachments-and-links:1880
rejected @ plugin:consistent-attachments-and-links:24
Promise.then (async)
step @ plugin:consistent-attachments-and-links:25
fulfilled @ plugin:consistent-attachments-and-links:23
Promise.then (async)
step @ plugin:consistent-attachments-and-links:25
fulfilled @ plugin:consistent-attachments-and-links:23
Promise.then (async)
step @ plugin:consistent-attachments-and-links:25
fulfilled @ plugin:consistent-attachments-and-links:23
Promise.then (async)
step @ plugin:consistent-attachments-and-links:25
fulfilled @ plugin:consistent-attachments-and-links:23
Promise.then (async)
step @ plugin:consistent-attachments-and-links:25
fulfilled @ plugin:consistent-attachments-and-links:23

```

**Comment by eemq** [comment] 2024-05-18 22:34
> Plugin no longer working: when I move markdown files to a new folder the **links** move with it to the user-defined _resource folder, but the links in the note are not properly updated and images can no longer be found.
> 
> Didn't used to do that. I'm noticing it since the update 2 days ago



> Plugin no longer working: when I move markdown files to a new folder the links move with it to the user-defined _resource folder, but the links in the note are not properly updated and images can no longer be found.
> 
> Didn't used to do that. I'm noticing it since the update 2 days ago

@Tesgin Did you mean that "the **images** move with it to the user-defined _resource folder" but that links are not updating in the note itself?? Because this is what's happening to me. @mnaoumov please see error above that i captured from my console logs. Hope it can provide some insights to how to resolve this issue.

**Comment by mnaoumov** [comment] 2024-08-05 23:35
Fixed in https://github.com/dy-sh/obsidian-consistent-attachments-and-links/releases/tag/2.0.0

**Closed by mnaoumov** 2024-08-05 23:35 UTC
